---
title: "project"
author: "anina, margaret"
date: '2022-11-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

Fires = read.csv("FW_Veg_Rem_Combined.csv")
library(ggplot2)
library(tidyverse)
library(maps)
library(ggmap)
library(ggthemes)
library(usdata)
library(lubridate)
library(stringr)
library(usmap)
```


## Data Cleaning

```{r}
FiresClean <- Fires %>%
  mutate(discovery_month = fct_relevel(discovery_month, c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')), 
         disc_pre_month = fct_relevel(disc_pre_month, c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')), 
         days_to_containment =  str_remove(putout_time, "\\ .*")) %>%
  mutate(fire_size_class = factor(fire_size_class), 
         stat_cause_descr = factor(stat_cause_descr), 
         state = factor(state), 
         vegCat = case_when(Vegetation %in% c(1, 2, 3, 4, 5, 6, 7, 16, 17, 18, 19, 20, 21, 22) ~ 'forest', 
                            Vegetation %in% c(24, 25, 26, 27) ~ 'agricultural', 
                            Vegetation == 28 ~ 'urban', 
                            Vegetation == 23 ~ 'water', 
                            Vegetation == 13 ~ 'tundra', 
                            Vegetation %in% c(14, 15) ~ 'desert', 
                            Vegetation %in% c(9, 10) ~ 'grassland',
                            Vegetation %in% c(11, 12) ~ 'shrubland', 
                            Vegetation == 8 ~ 'savanna', 
                            Vegetation == 0 ~ 'unknown'), 
         forestType = case_when(Vegetation %in% c(2, 5, 7, 17, 20, 22) ~ 'deciduous', 
                                Vegetation %in% c(1, 3, 4, 6, 16, 18, 19, 21) ~ 'evergreen'), 
         forestLeafType = case_when(Vegetation %in% c(1, 2, 3, 5, 16, 17, 18, 20) ~ 'broadleaf', 
                                    Vegetation %in% c(4, 6, 7, 19, 21, 22) ~ 'needleleaf'), 
         causeCat = case_when(stat_cause_descr %in% c('Arson') ~ 'Intentional Human Action', 
                              stat_cause_descr %in% c('Campfire', 'Children', 'Equipment Use', 'Fireworks', 'Smoking') ~ 'Unintentional Human Action', 
                              stat_cause_descr %in% c('Powerline', 'Railroad', 'Structure') ~ 'Infrastructure', 
                              stat_cause_descr %in% c('Lightning', 'Debris Burning') ~ 'Natural Causes', 
                              stat_cause_descr %in% c('Miscellaneous', 'Missing/Undefined') ~ 'Other'))

FiresClean$disc_clean_date <- as_date(FiresClean$disc_clean_date, format = '%m/%d/%Y')
FiresClean$cont_clean_date <- as_date(FiresClean$cont_clean_date, format = '%m/%d/%Y')
FiresClean$disc_date_pre <- as_date(FiresClean$disc_date_pre, format = '%m/%d/%Y')
FiresClean$disc_date_final <- as_date(FiresClean$disc_date_final, format = '%m/%d/%Y %h:%M')
FiresClean$cont_date_final <- as_date(FiresClean$cont_date_final, format = '%m/%d/%Y %h:%M')
```

## Exploratory Visualizations

```{r}
ggplot(FiresClean, aes(x = discovery_month, fill = stat_cause_descr)) +
  geom_bar(color = 'dimgray') + 
  labs(x = 'Month of Fire Discovery', y = 'Number of Fires', title = 'Number of Fires and Fire Cause by Month', fill = 'Fire Cause') +
  theme_classic()

ggplot(FiresClean, aes(x = discovery_month, fill = causeCat)) +
  geom_bar(color = 'dimgray') + 
  labs(x = 'Month of Fire Discovery', y = 'Number of Fires', title = 'Number of Fires and Fire Cause by Month', fill = 'Fire Cause') +
  theme_classic()

ggplot(FiresClean, aes(x = yday(disc_clean_date), fill = causeCat)) +
  geom_density(alpha = .5) + 
  labs(x = 'Month of Fire Discovery', y = 'Number of Fires', title = 'Number of Fires and Fire Cause by Month', fill = 'Fire Cause') +
  facet_wrap(~causeCat) + 
  theme_classic() + 
  theme(legend.position = 'none')

ggplot(FiresClean, aes(x = disc_clean_date, fill = causeCat)) + 
  geom_density(alpha = .5) + 
  facet_wrap(~ causeCat) + 
  labs(x = 'Date of Fire Discovery', y = 'Density of Fires', title = 'Density of Fire Cause Over Time', fill = 'Fire Cause') +
  theme_classic() + 
  theme(legend.position = 'none') 
```

```{r}
continentalUS <- get_stamenmap(
  bbox = c(left = -126.47, bottom = 24.21, right = -65.74, top = 49.72),
  maptype = "terrain",
  zoom = 4)

Alaska <- get_stamenmap(
  bbox = c(left = -189.23, bottom = 50.4, right = -129.38, top = 71.52),
  maptype = "terrain",
  zoom = 5)

Hawaii <- get_stamenmap(
  bbox = c(left = -160, bottom = 18.15, right = -154, top = 22.6),
  maptype = "terrain",
  zoom = 7)

PuertoRico <- get_stamenmap(
  bbox = c(left = -67.7, bottom = 17.17, right = -65, top = 19.14),
  maptype = "terrain",
  zoom = 8)
```


```{r}
ggmap(continentalUS) + 
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude),
    alpha = .4,
    size = 0.2
  ) +
  theme_map()

ggmap(Alaska) + 
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude),
    alpha = .8,
    size = 0.7
  ) +
  theme_map()

ggmap(Hawaii) + 
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude),
    alpha = .8,
    size = 1
  ) +
  theme_map()

ggmap(PuertoRico) + 
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude),
    alpha = .8,
    size = 1
  ) +
  theme_map()
```

```{r}
ggmap(continentalUS) + 
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude, color = fire_mag),
    alpha = .2,
    size = 0.2
  ) +
  theme_map()

ggmap(Alaska) +
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude, color = fire_mag),
    alpha = .8,
    size = 0.7
  ) +
  theme_map()

ggmap(Hawaii) +
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude, color = fire_mag),
    alpha = .8,
    size = 1
  ) +
  theme_map()

ggmap(PuertoRico) +
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude, color = fire_mag),
    alpha = .8,
    size = 1
  ) +
  theme_map()
```

```{r}
ggmap(continentalUS) + 
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude, color = fire_size_class),
    alpha = .4,
    size = 0.2
  ) +
  theme_map() +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 0.8)))
# want to change legend labels to definitions for fire size class

ggmap(Alaska) +
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude, color = fire_size_class),
    alpha = .8,
    size = 0.7
  ) +
  theme_map() +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 0.8)))

ggmap(Hawaii) +
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude, color = fire_size_class),
    alpha = .8,
    size = 1
  ) +
  theme_map() +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 0.8)))

ggmap(PuertoRico) +
  geom_point(
    data = FiresClean,
    aes(x = longitude, y = latitude, color = fire_size_class),
    alpha = .8,
    size = 1
  ) +
  theme_map() +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 0.8)))
```


```{r}
# MOST COMMON CAUSE OF FIRE BY STATE
FiresCleanState <- FiresClean %>% 
  group_by(state, causeCat) %>% 
  summarize(num_by_cause = n())

FiresCleanGroup <- FiresCleanState %>% 
  group_by(state) %>% 
  filter(num_by_cause == max(num_by_cause)) # need to deal with MA, DE

FiresCleanGroup <- FiresCleanGroup %>%
  ungroup() %>% 
  filter(!state %in% c('DE', 'MA')) %>% # takes out DE and MA
  add_row(state = "DE", # re-adds DE
          causeCat = "Intentional Human Action, Unintentional Human Action, Other", 
          num_by_cause = 3) %>%
  add_row(state = "MA", # re-adds MA
          causeCat = "Unintentional Human Action, Other", 
          num_by_cause = 24) 
  
plot_usmap(data = FiresCleanGroup, values = "causeCat", color = "black") +
  scale_fill_manual(values = c("#1b6c6b","green", "#1ccbd1", "#bcdfc6", "#e8f7eb"),
                    # https://huemint.com/gradient-5/ #00a7a0
                    breaks = c("Natural Causes", 
                               "Other", 
                               "Intentional Human Action", 
                               "Unintentional Human Action, Other",
                               "Intentional Human Action, Unintentional Human Action, Other"),
                    labels = c("Natural Causes: lightning, debris burning", 
                               "Other: miscellaneous, missing/undefined", 
                               "Intentional Human Action: arson", 
                               "Tie: Unintentional Human Action, Other (MA)",
                               "Tie: Intentional Human Action, Unintentional Human Action, Other (DE)"),
                    name = "Cause of Wildfire") +
  theme(legend.position = "right") +
  labs(title = "Most Common Cause of Wildfire by State (1992-2015)", 
       caption = "Data from federal, state, and local fire organizations in the US. \n Graphic made by Margaret Shepherd. \n Unintentional Human Action consists of campfires, children, equipment use, \n fireworks, and smoking.")
```

```{r}
ggplot(FiresClean, aes(x = yday(disc_clean_date), fill = vegCat)) +
  geom_density(alpha = .5) + 
  labs(x = 'Month of Fire Discovery', y = 'Number of Fires', title = 'Number of Fires and Surrounding Vegetation by Month', fill = 'Vegetation') +
  facet_wrap(~vegCat) + 
  theme_classic() + 
  theme(legend.position = 'none')

ggplot(FiresClean, aes(x = yday(disc_clean_date), fill = fire_size_class)) +
  geom_density(alpha = .5) + 
  labs(x = 'Month of Fire Discovery', y = 'Number of Fires', title = 'Number of Fires and Fire Size Class by Month', fill = 'Fire Size Class') +
  facet_wrap(~fire_size_class) + 
  theme_classic() + 
  theme(legend.position = 'none')
```

```{r}
FiresCleanVeg <- FiresClean %>% 
  group_by(vegCat) %>% 
  summarize(num = n())

ggplot(FiresCleanVeg, aes(x = vegCat)) +
  geom_col(aes(y = num)) +
  labs(x = 'Surrounding Vegetation',
       y = 'Number of Fires',
       title = 'Number of Fires by Surrounding Vegetation')
```

```{r}
FiresCleanCause <- FiresClean %>% 
  group_by(causeCat) %>% 
  summarize(num = n())

ggplot(FiresCleanCause, aes(x = causeCat)) +
  geom_col(aes(y = num)) +
  labs(x = 'Fire Cause',
       y = 'Number of Fires',
       title = 'Number of Fires by Fire Cause (grouped)')
```

```{r}
FiresCause <- FiresClean %>% 
  group_by(stat_cause_descr) %>% 
  summarize(num = n())

ggplot(FiresCause, aes(x = stat_cause_descr)) +
  geom_col(aes(y = num)) +
  labs(x = 'Fire Cause',
       y = 'Number of Fires',
       title = 'Number of Fires by Fire Cause (ungrouped)') +
  theme(axis.text.x = element_text(angle = 45, hjust=1))
```

```{r}
Fires_temp <- FiresClean %>% 
  filter(weather_file != 'File Not Found') %>% 
  filter(Temp_pre_30 != 0) %>% 
  filter(Temp_pre_15 != 0) %>%
  filter(Temp_pre_7 != 0) %>%
  filter(Temp_cont != 0) 
  # filter(Temp_pre_30 != 0 | Temp_pre_15 != 0 | Temp_pre_7 != 0 | Temp_cont != 0) # keeps row if all four temps are nonzero

Fires_wind <- FiresClean %>% 
  filter(weather_file != 'File Not Found') %>%
  filter(Wind_pre_30 != 0) %>% 
  filter(Wind_pre_15 != 0) %>%
  filter(Wind_pre_7 != 0) %>%
  filter(Wind_cont != 0)
  
Fires_hum <- FiresClean %>% 
  filter(weather_file != 'File Not Found') %>%
  filter(Hum_pre_30 != 0) %>% 
  filter(Hum_pre_15 != 0) %>%
  filter(Hum_pre_7 != 0) %>%
  filter(Hum_cont != 0)

Fires_prec <- FiresClean %>% 
  filter(weather_file != 'File Not Found') %>%
  filter(Prec_pre_30 != 0) %>% 
  filter(Prec_pre_15 != 0) %>%
  filter(Prec_pre_7 != 0) %>%
  filter(Prec_cont != 0)

(avgtemp30 = mean(Fires_temp$Temp_pre_30))
(avgtemp15 = mean(Fires_temp$Temp_pre_15))
(avgtemp7 = mean(Fires_temp$Temp_pre_7))
(avgtempcont = mean(Fires_temp$Temp_cont))

(avgwind30 = mean(Fires_wind$Wind_pre_30))
(avgwind15 = mean(Fires_wind$Wind_pre_15))
(avgwind7 = mean(Fires_wind$Wind_pre_7))
(avgwindcont = mean(Fires_wind$Wind_cont))

(avghum30 = mean(Fires_hum$Hum_pre_30))
(avghum15 = mean(Fires_hum$Hum_pre_15))
(avghum7 = mean(Fires_hum$Hum_pre_7))
(avghumcont = mean(Fires_hum$Hum_cont))

(avgprec30 = mean(Fires_prec$Prec_pre_30))
(avgprec15 = mean(Fires_prec$Prec_pre_15))
(avgprec7 = mean(Fires_prec$Prec_pre_7))
(avgpreccont = mean(Fires_prec$Prec_cont))

days_before <- c(30, 15, 7, 0)
temp <- c(avgtemp30, avgtemp15, avgtemp7, avgtempcont)
wind <- c(avgwind30, avgwind15, avgwind7, avgwindcont)
hum <- c(avghum30, avghum15, avghum7, avghumcont)
prec <- c(avgprec30, avgprec15, avgprec7, avgpreccont)
avg_weather <- data.frame(days_before, temp, wind, hum, prec)
```

```{r}
ggplot(data = avg_weather, aes(x = days_before, y = temp)) +
  geom_point() +
  xlim(30, 0) +
  labs(x = 'Number of Days Before a Wildfire',
       y = 'Average Temperature (C) at Wildfire Location',
       title = 'Average Temperature Before a Wildfire \n Wildfires in the US, 1992-2015')

ggplot(data = avg_weather, aes(x = days_before, y = wind)) +
  geom_point() +
  xlim(30, 0) +
  labs(x = 'Number of Days Before a Wildfire',
       y = 'Average Wind Speed (m/s) at Wildfire Location',
       title = 'Average Wind Speed Before a Wildfire \n Wildfires in the US, 1992-2015')

ggplot(data = avg_weather, aes(x = days_before, y = hum)) +
  geom_point() +
  xlim(30, 0) +
  labs(x = 'Number of Days Before a Wildfire',
       y = 'Average Humidity (%) at Wildfire Location',
       title = 'Average Humidity Before a Wildfire \n Wildfires in the US, 1992-2015')

ggplot(data = avg_weather, aes(x = days_before, y = prec)) +
  geom_point() +
  xlim(30, 0) +
  labs(x = 'Number of Days Before a Wildfire',
       y = 'Average Precipitation (mm) at Wildfire Location',
       title = 'Average Precipitation Before a Wildfire \n Wildfires in the US, 1992-2015')
```


